# service/user
url: http://localhost:8080
wallet-name: my_wallet_name
wallet-key: 6cih1cVgRH8yHD54nEYyPKLmdv67o8QbufxaTHot3Qxp
email: my_wallet_email

# connect
pw-name: my_pairwise_name
pw-key: my_pairwise_key
pw-endp: pairwise endpoint

# send
msg: hello

# create schema
schema-name: my_schema
schema-attrs: ["field1", "field2", "field3"]
schema-v: "1.0"

# create creddef
tag: my_creddef
schema-id: P4GfWWZCgWZYtAyZzjQPVm:2:my_schema:1.0

# agency
genesis: genesis_path