# service/user
url: http://localhost:8080
wallet-name: my_wallet_name
wallet-key: 6cih1cVgRH8yHD54nEYyPKLmdv67o8QbufxaTHot3Qxp
email: my_wallet_email

# connect
pairwise-name: my_pairwise_name
pairwise-key: my_pairwise_key
pairwise-endpoint: pairwise endpoint

# send
msg: hello

# create schema
schema-name: my_schema
schema-attrs: ["field1", "field2", "field3"]
schema-version: "1.0"

# create creddef
creddef-tag: my_creddef
schema-id: P4GfWWZCgWZYtAyZzjQPVm:2:my_schema:1.0

# agency
genesis-filepath: genesis_path