# service/user
url: http://localhost:8080
walletname: my_wallet_name
walletkey: 6cih1cVgRH8yHD54nEYyPKLmdv67o8QbufxaTHot3Qxp
email: my_wallet_email

# connect
pwname: my_pairwise_name
pwkey: my_pairwise_key
pwendp: pairwise endpoint

# send
msg: hello

# create schema
schName: my_schema
schAttrs: ["field1", "field2", "field3"]
schV: "1.0"

# create creddef
tag: my_creddef
schID: P4GfWWZCgWZYtAyZzjQPVm:2:my_schema:1.0

# agency
genesis: genesis_path