Resources:
  EnvBeanstalkApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref EnvBeanstalkApplication
      SourceBundle:
        S3Bucket: !Join
          - ""
          - - "findy-agency-beanstalk-configuration-"
            - !Ref "AWS::AccountId"
        S3Key: Dockerrun.zip
  EnvBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: findy-agency
      ResourceLifecycleConfig:
        ServiceRole: !Join
          - ""
          - - "arn:aws:iam::"
            - !Ref "AWS::AccountId"
            - ":role/aws-service-role/elasticbeanstalk.amazonaws.com/AWSServiceRoleForElasticBeanstalk"
        VersionLifecycleConfig:
          MaxAgeRule:
            Enabled: true
            MaxAgeInDays: 3
Outputs:
  AppVersion:
    Description: Application Version Label
    Value: !Ref EnvBeanstalkApplicationVersion
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", AppVersion]]
