name: e2e test
on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          repository: findy-network/findy-wrapper-go
          token: ${{ secrets.repository_token }}
          path: findy-wrapper-go
          ref: dev

      - uses: actions/checkout@v2
        with:
          repository: findy-network/findy-agent
          token: ${{ secrets.repository_token }}
          path: findy-agent
          ref: dev

      - uses: actions/checkout@v2
        with:
          path: findy-agent-cli

      - name: Ledger
        run: ./findy-agent-cli/scripts/dev/e2e-test.sh dev_ledger

      - name: Build
        run: docker build -t e2e:latest -f ./findy-agent-cli/action/e2e/Dockerfile .

      - name: e2e test
        run: docker run --network="host" e2e:latest
