name: test
on: push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51.1
          args: --timeout=5m
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: checkout
        uses: actions/checkout@v3
      - name: test and measure coverage
        run: make test_cov_out
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.txt
      - name: scan
        run: make scan | grep "Licensing OK"
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: checkout
        uses: actions/checkout@v3
      - name: set up agency
        run: |
          cd scripts/fullstack
          docker-compose up -d
      - name: install
        run: |
          make install
          ~/go/bin/findy-agent-cli --version
      - name: test
        run: | # TODO: move to script file and create extensive e2e tests
          cd ./scripts/fullstack
          source ./setup-cli-env.sh 
          ./make-agent.sh acme
          ./make-agent.sh faber
          conn_id=$(acme/invitation | faber/connect)
          cd acme/$conn_id
          $FCLI connection trustping
        env:
          FCLI: "/home/runner/go/bin/findy-agent-cli"
