name: test
on: push
env:
  GOPRIVATE: "github.com/findy-network/*"
jobs:
  test:
    runs-on: ubuntu-latest
    #    container: optechlab/indy-golang:1.16.0
    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: checkout
        uses: actions/checkout@v2
      - name: use token
        run: git config --global url."https://"${{ secrets.https_prefix }}"github.com/".insteadOf "https://github.com/"
      - name: test
        run: make test
      - name: scan
        run: make scan
